#ADD in user.py the view all function SOLVED
#FIX THE USER SELECT in "VM" FUNCTION, RIGHT NOW IT COUNT ONLY INTEGER


#IN TASK_MANAGER WHEN I RETRIEVE THE LEN(TASK_LIST) IT GIVES ME BACK ALL THE TASKS, CHANGE IT FOR THE ONE RELATIVE TO THE USER